jobs:
# Replace params / app_name with your heroku app name
- name: deploy-app
  plan:
  - aggregate:
    - get: pokemon-app
    - get: exam-infra-master
      trigger: true
  - task: mvn_build
    file: exam-infra-master/concourse/java/task.yml
    input_mapping: {source: pokemon-app}

  - task: push_to_heroku
    file: exam-infra-master/concourse/heroku/push_master_to_heroku.yml
    input_mapping: {source: pokemon-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))


- name: infra
  plan:
  - aggregate:
    - get: exam-infra-master
  - task: apply
    file: exam-infra-master/concourse/terraform/task.yml
    input_mapping: {source: exam-infra-master}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      statuscake_api_key: ((statuscake_api_key))
      command: apply
      directories: |
          terraform
  - put: exam-infra-master
    params:
      repository: with-state
      rebase: true

resources:

# Replace with your own repository
- name: pokemon-app
  type: git
  source:
      uri: git@github.com:synend16/pokemon.git
      branch: master
      private_key: ((deploy_key_app))

# Replace with your own repository
- name: exam-infra-master
  type: git
  source:
      uri: git@github.com:synend16/pgr301-exam-infra.git
      branch: master
      private_key: ((deploy_key_infra))
